### ISSUE TITLE
 Support for ST7789

### ISSUE THREAD

**Issue by kh0987** [vindar/ILI9341_T4#18]
Hello, I have an LCD with ST7789 controller and I would like to run LVGL on it. My project needs high performance UI, and so far the only other thing I've found using ST7789 with LVGL on Teensy 4.X platform is st7789_t3, which results in low performance. I've seen in some libraries' code that the difference between them might not be so big.

Is there a way to port this library to work with ST7789? I don't need tearing prevention, just the performance is important to me.

Thanks.

**Comment by vindar** [comment]
Hi, 

I have not tried it personally it but it seems my ILI9342_T4 library (which is a direct port of this library) "almost" work with the ST7789V display... c.f. [this post](https://github.com/vindar/ILI9341_T4/issues/14#issuecomment-1632624369). 

I expect I will attempt to port the library to ST7789 at some point but probably not before a couple of months as I am busy right now... 

Anyway, if you try it, I am interested to know what works/breaks with this display controller.

Best,
