### ISSUE TITLE
examples/lvgl_touch_minimal/lvgl_touch_minimal.ino  no longer compiles with latest lvgl release

### ISSUE THREAD

**Issue by dbonin360** [vindar/ILI9341_T4#19]
Just wanted to give you a heads up.  lvgl changed or removed some functions - I'm sure with your level of expertise you can get this working again, if need be.
Thanks for all your work!

**Comment by vindar** [comment]
Hi, 

Thanks for the heads up . 

I finally updated the example to work with the new LVGL API (tested with v9.2).
